-ifndef(erlang_srv_protocol).
-define(erlang_srv_protocol, true).

-define(JSON_RPC, <<"2.0">>).

%% Response error codes
-define(REC_PARSE_ERROR, -32700).
-define(REC_INVALID_REQUEST, -32600).
-define(REC_METHOD_NOT_FOUND, -32601).
-define(REC_INVALID_PARAMS, -32602).
-define(REC_INTERNAL_ERROR, -32603).
-define(REC_SERVER_ERROR_START, -32099).
-define(REC_SERVER_ERROR_END, -32000).
-define(REC_SERVER_NOT_INITIALIZED, -32002).
-define(REC_UNKNOWN_ERROR_CODE, -32001).
-define(REC_REQUEST_CANCELLED, -32800).
-define(REC_CONTENT_MODIFIED, -32801).

%% Text document sync kind
-define(TEXT_DOCUMENT_SYNC_KIND_NONE, 0).
-define(TEXT_DOCUMENT_SYNC_KIND_FULL, 1).
-define(TEXT_DOCUMENT_SYNC_KIND_INCREMENTAL, 2).

%% Completion item kind
-define(COMPLETION_ITEM_KIND_TEXT, 1).
-define(COMPLETION_ITEM_KIND_METHOD, 2).
-define(COMPLETION_ITEM_KIND_FUNCTION, 3).
-define(COMPLETION_ITEM_KIND_CONSTRUCTOR, 4).
-define(COMPLETION_ITEM_KIND_FIELD, 5).
-define(COMPLETION_ITEM_KIND_VARIABLE, 6).
-define(COMPLETION_ITEM_KIND_CLASS, 7).
-define(COMPLETION_ITEM_KIND_INTERFACE, 8).
-define(COMPLETION_ITEM_KIND_MODULE, 9).
-define(COMPLETION_ITEM_KIND_PROPERTY, 10).
-define(COMPLETION_ITEM_KIND_UNIT, 11).
-define(COMPLETION_ITEM_KIND_VALUE, 12).
-define(COMPLETION_ITEM_KIND_ENUM, 13).
-define(COMPLETION_ITEM_KIND_KEYWORD, 14).
-define(COMPLETION_ITEM_KIND_SNIPPET, 15).
-define(COMPLETION_ITEM_KIND_COLOR, 16).
-define(COMPLETION_ITEM_KIND_FILE, 17).
-define(COMPLETION_ITEM_KIND_REFERENCE, 18).
-define(COMPLETION_ITEM_KIND_FOLDER, 19).
-define(COMPLETION_ITEM_KIND_ENUM_MEMBER, 20).
-define(COMPLETION_ITEM_KIND_CONSTANT, 21).
-define(COMPLETION_ITEM_KIND_STRUCT, 22).
-define(COMPLETION_ITEM_KIND_EVENT, 23).
-define(COMPLETION_ITEM_KIND_OPERATOR, 24).
-define(COMPLETION_ITEM_KIND_TYPE_PARAM, 25).

%% Symbol kind
-define(SYMBOL_KIND_FILE, 1).
-define(SYMBOL_KIND_MODULE, 2).
-define(SYMBOL_KIND_NAMESPACE, 3).
-define(SYMBOL_KIND_PACKAGE, 4).
-define(SYMBOL_KIND_CLASS, 5).
-define(SYMBOL_KIND_METHOD, 6).
-define(SYMBOL_KIND_PROPERTY, 7).
-define(SYMBOL_KIND_FIELD, 8).
-define(SYMBOL_KIND_CONSTRUCTOR, 9).
-define(SYMBOL_KIND_ENUM, 10).
-define(SYMBOL_KIND_INTERFACE, 11).
-define(SYMBOL_KIND_FUNCTION, 12).
-define(SYMBOL_KIND_VARIABLE, 13).
-define(SYMBOL_KIND_CONSTANT, 14).
-define(SYMBOL_KIND_STRING, 15).
-define(SYMBOL_KIND_NUMBER, 16).
-define(SYMBOL_KIND_BOOLEAN, 17).
-define(SYMBOL_KIND_ARRAY, 18).
-define(SYMBOL_KIND_OBJECT, 19).
-define(SYMBOL_KIND_KEY, 20).
-define(SYMBOL_KIND_NULL, 21).
-define(SYMBOL_KIND_ENUMMEMBER, 22).
-define(SYMBOL_KIND_STRUCT, 23).
-define(SYMBOL_KIND_EVENT, 24).
-define(SYMBOL_KIND_OPERATOR, 25).
-define(SYMBOL_KIND_TYPE_PARAMETER, 26).

%% Insert text format
-define(INSERT_TEXT_FORMAT_PLAIN, 1).
-define(INSERT_TEXT_FORMAT_SNIPPET, 2).

%% Highlight kind
-define(HIGHLIGHT_KIND_TEXT, 1).
-define(HIGHLIGHT_KIND_READ, 2).
-define(HIGHLIGHT_KIND_WRITE, 3).

%% Message type
-define(MESSAGE_TYPE_ERROR, 1).
-define(MESSAGE_TYPE_WARNING, 2).
-define(MESSAGE_TYPE_INFO, 3).
-define(MESSAGE_TYPE_LOG, 4).

-endif.
